### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by DharshuAlagar23**
Hi Boss,
I have completed my front-end part.Can you please review it,and let me know necessary changes.
Thank you.

### CODE REVIEW

**Review by Jenishrz — APPROVED** [review]
Hi Dharshana,
Yes, I reviewed your code and In that you have to add the script code line for specific font family. please update it.

**Comment by Jenishrz** [comment]
> Hi Dharshana, Yes, I reviewed your code and In that you have to add the script code line for specific font family. please update it.
Thank you.

**Comment by DharshuAlagar23** [comment]
> > Hi Dharshana, Yes, I reviewed your code and In that you have to add the script code line for specific font family. please update it.
> > Thank you.

Hi Boss,
Now I made the changes in my code and added the script line in index.html.Can you please check it and update me to merge the pull request.
Thank you.

**Comment by Jenishrz** [comment]
> > > Hi Dharshana, Yes, I reviewed your code and In that you have to add the script code line for specific font family. please update it.
> > > Thank you.
> 
> Hi Boss, Now I made the changes in my code and added the script line in index.html.Can you please check it and update me to merge the pull request. Thank you.

Hi Dharshana,
Yes, Now your code is fine. And you can merge the pull request and close it.
Thank you.

**Comment by DharshuAlagar23** [comment]
Hi Boss,
I have merged and closed the pull request.
Thank you.

**Pull request merged**
